<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/07 10:55:24

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root:root@localhost/mail',
), 'propel');
$this->databases['propel'] = $database;
